version: '3'
services:
  # #################
  # Storage services
  # #################
  mongo:
    container_name: mongo
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - pi_net
    volumes:
      - mongo_data:/data/db
  # #################
  # Backend services
  # #################
  ms_auth:
    container_name: ms_auth
    build:
      context: ./ms_auth
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - pi_net
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=PI-DB-Users
  ms_user:
    container_name: ms_user
    build:
      context: ./ms_user
    restart: on-failure
    ports:
      - "8001:8001"
    networks:
      - pi_net
    depends_on:
      - mongo
      - ms_auth
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=PI-DB-Users
  ms_quiz:
    container_name: ms_quiz
    build:
      context: ./ms_quiz
    restart: on-failure
    ports:
      - "8002:8002"
    networks:
      - pi_net
    depends_on:
      - mongo
      - ms_auth
      - ms_user
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017
      - SPRING_DATA_MONGODB_DATABASE=PI-DB-Quizes

volumes:
  mongo_data:

networks:
  pi_net:
    driver: bridge