server:
  port: 8001

microservice:
  user:
    name: User
    version: v1
    description: Responsible for user management
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi

jwt:
  private:
    key: classpath:private.key
  public:
    key: classpath:public.pub