export enum QuizType {
    QUIZ_MULTIPLE_CHOICE = 'QUIZ_MULTIPLE_CHOICE',
    QUIZ_FILL_SPACE = 'QUIZ_FILL_SPACE',
    QUIZ_OPEN = 'QUIZ_OPEN',
    QUIZ_POLL = 'QUIZ_POLL',
    QUIZ_TRUE_FALSE = 'QUIZ_TRUE_FALSE',
    QUIZ_WORD_CLOUD = 'QUIZ_WORD_CLOUD'
}

export enum SlideType {
    SLIDE_TEXT_1 = 'SLIDE_TEXT_1',
    SLIDE_TEXT_2 = 'SLIDE_TEXT_2',
    SLIDE_TEXT_MEDIA_1 = 'SLIDE_TEXT_MEDIA_1',
    SLIDE_TEXT_MEDIA_2 = 'SLIDE_TEXT_MEDIA_2',
    SLIDE_TITLE_1 = 'SLIDE_TITLE_1',
    SLIDE_TITLE_2 = 'SLIDE_TITLE_2'
}

export enum StatusItem {
    DONE = 'DONE',
    PENDING = 'PENDING'
}