server:
  port: 8000

microservice:
  auth:
    name: auth
    version: v1
    description: Responsible for user management, authentication and authorization
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi

jwt:
  private:
    key: classpath:private.key
  public:
    key: classpath:public.pub

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}
      database: ${SPRING_DATA_MONGODB_DATABASE:PI-C-Users}