name: Core Pipeline
on:
  push:
    branches: [ "v00.00.000" ]
    paths:
      - 'backend/core/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "v00.00.000" ]
    paths:
      - 'backend/core/**'
      - '.github/workflows/**'

jobs:
  UnitaryTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'
      - name: Execute Unitary Tests Core
        run: |
          cd backend
          mvn -pl core clean package verify -Dtest="**/*UnitaryTest*"

  IntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'
      - name: Run Integration Tests
        run: |
          cd backend
          mvn -pl core test -Dtest="**/*IntegrationTest*"

  AcceptanceTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'
      - name: Run Acceptance Tests
        run: |
          cd backend
          mvn -pl core test -Dtest="**/*AcceptanceTest*"